data <- read.table("./household_power_consumption.txt", sep= ";", header = TRUE, stringsAsFactors = FALSE, na.string = "?")
data$DateTime <- strptime(paste(data$Date, data$Time),format="%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
dfplot <- data[(data$Date == "2007-02-01") | (data$Date == "2007-02-02"),]
Sys.setlocale(category = "LC_TIME", locale = "C")
png(filename = "plot3.png")
plot(dfplot$DateTime,dfplot$Sub_metering_1, type="n", ylab = "Energy sub metering", xlab = "")
lines(dfplot$DateTime,dfplot$Sub_metering_1, type = "l", col = "black")
lines(dfplot$DateTime,dfplot$Sub_metering_2, type = "l", col = "red")
lines(dfplot$DateTime,dfplot$Sub_metering_3, type = "l", col = "blue")
legend("topright", lwd = 1, legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","blue","red"))
dev.off()
